spring:
  application:
    name: oscp-monitor
  security:
    user:
      name: JOKER
      password: JOKER

  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}

server:
  port: 8008

eureka:
  client:
    service-url:
      defaultZone: http://39.106.197.145:8000/eureka/