spring:
  application:
    name: oscp-config-center
  cloud:
    config:
      uri:
server:
  port: 8002

eureka:
  client:
    service-url:
      #      defaultZone: http://localhost:8000/eureka/
      defaultZone: http://39.106.197.145:8000/eureka/