spring:
  application:
    name: oscp-gateway-center

server:
  port: 8001


jwt:
  header: X-Auth-Token   #jwt的请求头
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3Jl   #jwt的加密字符串
  expiration: 60480000   #7天 单位:秒 3600000
  auth-path: auth

ignoreList:
  ignore-url: /auth,/oscp,/test,/film/getIndex,/film/getConditionList,/film/getFilms,/film/films,/cinema/getCinemas,/cinema/getCondition,/cinema/getFields,/cinema/getFieldInfo #忽略列表



