spring:
  application:
    name: oscp-gateway-center
  datasource:
    url: jdbc:mysql://localhost:3306/local_dome_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

server:
  port: 8001
  tomcat:
    basedir: ${user.home}/tomcat/tmp

jwt:
  header: X-Auth-Token   #jwt的请求头
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3Jl   #jwt的加密字符串
  expiration: 60480000   #7天 单位:秒 3600000
  auth-path: auth

ignoreList:
  ignore-url: /checkUsername,/auth,/oscp/user/register,/oscp/community/getAllActivityReply,/oscp/community/getLatestActivity,/oscp/film/getIndex,/oscp/film/getConditionList,/oscp/film/getFilms,/oscp/film/films,/oscp/cinema/getFieldInfo,/oscp/cinema/getCinemas,/oscp/cinema/getCondition,/oscp/cinema/getFields #忽略列表







